#!/bin/bash

dotfiles=(".bashrc" ".vimrc" ".tmux.conf")
force=""

if [ "$1" == "-f" ]; then
    force="$1"
fi

echo "Symlinking to $HOME/"
for i in "${dotfiles[@]}"; do
    echo "    $i"
    ln -s $force $PWD/$i $HOME/
done

echo -n "Install packages from the pkglist file? [y/N]: "
read answer

if [ "$answer" != "${answer#[Yy]}" ]; then
    sudo dnf install $(cat pkglist)
else
    echo "Skipping package installation"
fi

echo "Done!"
