#! /bin/sh

sxhkd &
dunst &
# xfce4-panel &
wmname LG3D & # Android SDK GUI fails without this
compton -c &
feh --bg-fill Pictures/backgrounds/ronja-laivalla.jpg
xsetroot -solid "slate gray"

help=$HOME/.dotfiles/README.pdf

# Open the help pdf on startup
# mupdf help || evince help || okular help || xpdf help &

# bspc monitor -d 0001 0010 0011 0100 0101 0110 0111 1000 1001 0000
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color '#444444'
bspc config active_border_color '#444444'
bspc config focused_border_color '#928374'

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
