#! /bin/sh

sxhkd &
dunst &
wmname LG3D &
# compton &
# xfce4-panel &
tint2 &
# nm-applet &
# pasystray &
# wal -R &
# feh --bg-fill ~/Pictures/backgrounds/real-space.jpg
xsetroot -solid "light coral"

help=$HOME/.dotfiles/README.pdf

# avaa apustus-pdf käynnistäessä
# jos oot tosi fuksi xD
# mupdf help || evince help || okular help || xpdf help &

# bspc monitor -d 0001 0010 0011 0100 0101 0110 0111 1000 1001 0000
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#161315"
bspc config active_border_color "#161315"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
