#! /bin/sh

sxhkd &
dunst &
# compton &
# xfce4-panel &
# nm-applet &
wal -R &

apu=$HOME/.dotfiles/sxhkd-binds.pdf

# avaa apustus-pdf käynnistäessä
# jos oot tosi fuksi xD
# mupdf apu || evince apu || okular apu || xpdf apu &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
